# Generated by Django 2.1.1 on 2018-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0002_remove_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
