# Generated by Django 2.1.1 on 2018-09-26 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0004_person_brithday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='brithday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
