# Generated by Django 2.1.1 on 2018-09-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0005_auto_20180926_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='upload',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
