# Generated by Django 2.1.1 on 2018-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0006_person_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='upload',
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.FileField(default='', upload_to='photo/'),
        ),
    ]
