# Generated by Django 2.1.1 on 2018-09-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0012_auto_20180927_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modelName',
            field=models.CharField(db_column='汽车型号', max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(db_column='工厂名字', max_length=20),
        ),
    ]
