# Generated by Django 2.1.1 on 2018-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0013_auto_20180927_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modelName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
