# Generated by Django 2.1.1 on 2018-09-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0014_auto_20180927_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=False),
        ),
    ]
