# Generated by Django 2.1.1 on 2018-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0016_auto_20180927_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='工厂名字'),
        ),
    ]
