# Generated by Django 2.1.1 on 2018-09-27 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0017_auto_20180927_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modelName',
            field=models.CharField(max_length=20, verbose_name='汽车类型'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='person',
            name='brithday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='曾用名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(default='', upload_to='media/', verbose_name='照片'),
        ),
    ]
