# Generated by Django 2.1.1 on 2018-09-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0018_auto_20180927_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_person_friends_+', to='AboutModel.Person'),
        ),
    ]
