# Generated by Django 2.1.1 on 2018-09-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0019_person_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='friends',
        ),
    ]
