# Generated by Django 2.1.1 on 2018-09-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0021_class_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(to='AboutModel.Student'),
        ),
    ]
