# Generated by Django 2.1.1 on 2018-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutModel', '0022_auto_20180927_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(blank=True, to='AboutModel.Student'),
        ),
    ]
