# Generated by Django 2.1.1 on 2018-10-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
